server:
  port: 8080
  servlet:
    context-path: /api/ragent

spring:
  application:
    name: ragent-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/ragent?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456

milvus:
  uri: http://localhost:19530

rag:
  default:
    collection-name: rag_default_store
    dimension: 4096
    metric-type: COSINE

  query-rewrite:
    enabled: true

ai:
  embedding:
    provider: siliconflow
    ollama:
      url: http://localhost:11434
      model: qwen3-embedding:8b-fp16
    siliconflow:
      url: https://api.siliconflow.cn/v1/embeddings
      api-key: sk-xlvfsxatnazrvtfqaklospaokrrohsuewwxgwrqvyxifpbpp
      model: Qwen/Qwen3-Embedding-8B
      dimension: 4096

  chat:
    provider: bailian
    ollama:
      url: http://localhost:11434
      model: qwen3:8b-fp16
    bailian:
      url: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
      api-key: sk-0e580b2e9e1f430f8948f55041f986e4
      model: qwen-plus-latest

  rerank:
    provider: bailian
    ollama:
      url: http://localhost:11434
      model: dengcao/Qwen3-Reranker-8B:F16
    bailian:
      url: https://dashscope.aliyuncs.com/api/v1/services/rerank/text-rerank/text-rerank
      api-key: sk-0e580b2e9e1f430f8948f55041f986e4
      model: qwen3-rerank

rustfs:
  url: http://localhost:9000
  access-key-id: rustfsadmin
  secret-access-key: rustfsadmin
